name: Daily Run - Price Puller Parts

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 07:00 UTC
  workflow_dispatch:

jobs:
  run-price-puller:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Parts_Puller_Parts.py script
        run: python "Parts_Puller_Parts.py"

      - name: Debug Excel file after script run
        run: |
          echo "Listing excel file info:"
          ls -l euro_parts_database.xlsx
          echo "File size (bytes):"
          stat --format=%s euro_parts_database.xlsx
          echo "File last modified time:"
          stat --format=%y euro_parts_database.xlsx

      - name: Configure Git and push changes
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add euro_parts_database.xlsx price_puller.log
          git commit -m "Update Excel file and log from daily run" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
